import { useState, useEffect } from "react";
import { entities, sendEmail } from '@/api/client';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Download, Send } from "lucide-react";
import StatCard from "@/components/StatCard";
import { HandCoins } from "lucide-react";
import { generateFinancialReportPDF } from "@/lib/financeReport";
import { isInRange, parseLocalDate, firstOfMonthLocalISO, todayLocalISO, makePdfMoneyFormatter } from "@/lib/finance";
import { useChurchSettings } from "@/lib/ChurchSettingsContext";
import { format } from "date-fns";
import { useBilling, UpgradePrompt } from "@/lib/billing";

export default function FinancialReportsPage() {
  // has({ plan: 'pro' }) — imperative plan check (Clerk B2B billing)
  const { has } = useBilling();
  const { fmt, settings } = useChurchSettings();
  const [giving, setGiving] = useState([]);
  const [expenditures, setExpenditures] = useState([]);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [fromDate, setFromDate] = useState(firstOfMonthLocalISO());
  const [toDate, setToDate] = useState(todayLocalISO());
  const [emailTarget, setEmailTarget] = useState("");

  useEffect(() => { loadData(); }, []);

  // Gate: Pro plan required (all hooks must be above this check)
  if (!has({ plan: 'pro' })) {
    return <UpgradePrompt plan="pro" message="Financial Reports are available on the Pro plan." />;
  }

  // Load the church's full history once; changing the From/To dates then filters
  // in memory so it feels instant (no spinner or refetch on every change).
  async function loadData() {
    setLoading(true);
    try {
      const [g, e] = await Promise.all([
        entities.Giving.list("-date", 100000),
        entities.Expenditure.list("-date", 100000),
      ]);
      setGiving(g); setExpenditures(e);
    } catch (err) {
      console.error("FinancialReports loadData failed:", err);
      setGiving([]); setExpenditures([]);
    } finally {
      setLoading(false);
    }
  }

  // ISO "YYYY-MM-DD" strings compare chronologically, so string <= is safe here.
  const rangeValid = !!fromDate && !!toDate && fromDate <= toDate;
  const periodLabel = rangeValid
    ? `${format(parseLocalDate(fromDate), "d MMM yyyy")} to ${format(parseLocalDate(toDate), "d MMM yyyy")}`
    : "—";

  // Timezone-safe range filtering — matches the shared PDF generator so the
  // on-screen figures and the downloaded/emailed report always agree.
  const filteredGiving = rangeValid ? giving.filter(g => isInRange(g.date, fromDate, toDate)) : [];
  const filteredExp = rangeValid ? expenditures.filter(e => isInRange(e.date, fromDate, toDate)) : [];

  const totalTithes = filteredGiving.filter(g=>g.type==="tithe").reduce((s,g)=>s+(g.amount||0),0);
  const totalOfferings = filteredGiving.filter(g=>g.type==="offering").reduce((s,g)=>s+(g.amount||0),0);
  const totalOthers = filteredGiving.filter(g=>g.type!=="tithe" && g.type!=="offering").reduce((s,g)=>s+(g.amount||0),0);
  const totalIncome = totalTithes + totalOfferings + totalOthers;
  const approvedExp = filteredExp.filter(e=>e.approval_status==="approved").reduce((s,e)=>s+(e.amount||0),0);
  const netBalance = totalIncome - approvedExp;

  function generatePDF() {
    if (!rangeValid) return;
    generateFinancialReportPDF({
      from: fromDate,
      to: toDate,
      giving,
      expenditures,
      fmt: makePdfMoneyFormatter(settings),
      churchName: settings?.church_name,
      splitOthers: true,
    });
  }

  async function handleSendEmail() {
    if (!emailTarget || !rangeValid) return;
    setSending(true);
    const body = `
      <h2>ChurchConnect — Financial Report (${periodLabel})</h2>
      <table border="1" cellpadding="8" style="border-collapse:collapse;width:100%">
        <tr><th>Item</th><th>Amount</th></tr>
        <tr><td>Total Tithes</td><td>${fmt(totalTithes)}</td></tr>
        <tr><td>Total Offerings</td><td>${fmt(totalOfferings)}</td></tr>
        <tr><td>Total Others</td><td>${fmt(totalOthers)}</td></tr>
        <tr><td>Total Income</td><td><strong>${fmt(totalIncome)}</strong></td></tr>
        <tr><td>Approved Expenditures</td><td>${fmt(approvedExp)}</td></tr>
        <tr><td><strong>Net Balance</strong></td><td><strong>${fmt(netBalance)}</strong></td></tr>
      </table>
      <p style="color:gray;font-size:12px">Generated by ChurchConnect CRM on ${format(new Date(),"MMMM d, yyyy")}</p>
    `;
    await sendEmail({
      to: emailTarget,
      subject: `Financial Report — ${periodLabel}`,
      body,
      from_name: "ChurchConnect"
    });
    setSending(false);
    alert("Report sent successfully!");
  }

  if (loading) return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" /></div>;

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div><h1 className="text-2xl font-bold">Financial Reports</h1><p className="text-muted-foreground text-sm">Generate and share financial summaries for any period</p></div>

      <div className="bg-white rounded-xl border border-border p-5 shadow-sm">
        <h2 className="font-semibold mb-4">Select Period</h2>
        <div className="flex flex-wrap gap-3 items-end">
          <div>
            <Label>From</Label>
            <Input type="date" value={fromDate} max={toDate || undefined} onChange={e => setFromDate(e.target.value)} className="w-44 mt-1" />
          </div>
          <div>
            <Label>To</Label>
            <Input type="date" value={toDate} min={fromDate || undefined} onChange={e => setToDate(e.target.value)} className="w-44 mt-1" />
          </div>
        </div>
        {!rangeValid && (
          <p className="text-sm text-destructive mt-3">Pick a valid period — the From date must be on or before the To date.</p>
        )}
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
        <StatCard title="Tithes" value={fmt(totalTithes)} icon={HandCoins} color="green" />
        <StatCard title="Offerings" value={fmt(totalOfferings)} icon={HandCoins} color="blue" />
        <StatCard title="Others" value={fmt(totalOthers)} icon={HandCoins} color="purple" />
        <StatCard title="Expenditures" value={fmt(approvedExp)} icon={HandCoins} color="red" />
        <StatCard title="Net Balance" value={fmt(netBalance)} icon={HandCoins} color={netBalance >= 0 ? "green" : "red"} />
      </div>

      <div className="bg-white rounded-xl border border-border p-5 shadow-sm space-y-4">
        <h2 className="font-semibold">Generate PDF Report</h2>
        <p className="text-muted-foreground text-sm">{filteredGiving.length} giving records and {filteredExp.length} expenditure records from {periodLabel}.</p>
        <Button onClick={generatePDF} disabled={!rangeValid} className="bg-primary text-primary-foreground gap-2">
          <Download className="w-4 h-4" />Download PDF Report
        </Button>
      </div>

      <div className="bg-white rounded-xl border border-border p-5 shadow-sm space-y-4">
        <h2 className="font-semibold">Send Report by Email</h2>
        <div className="flex gap-3 flex-wrap items-end">
          <div className="flex-1 min-w-48">
            <Label>Recipient Email</Label>
            <input type="email" value={emailTarget} onChange={e=>setEmailTarget(e.target.value)} placeholder="pastor@church.org" className="mt-1 w-full border border-input rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring" />
          </div>
          <Button onClick={handleSendEmail} disabled={!emailTarget || !rangeValid || sending} className="bg-primary text-primary-foreground gap-2">
            <Send className="w-4 h-4" />{sending ? "Sending..." : "Send Report"}
          </Button>
        </div>
      </div>
    </div>
  );
}
