import { useState, useEffect } from "react";
import { entities, sendEmail } from '@/api/client';
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { FileBarChart2, Download, Send } from "lucide-react";
import StatCard from "@/components/StatCard";
import { HandCoins } from "lucide-react";
import { generateFinancialReportPDF } from "@/lib/financeReport";
import { isInMonth } from "@/lib/finance";
import { useChurchSettings } from "@/lib/ChurchSettingsContext";
import { format } from "date-fns";
import { useBilling, UpgradePrompt } from "@/lib/billing";

const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const YEARS = [2023, 2024, 2025, 2026].map(String);

export default function FinancialReportsPage() {
  // has({ plan: 'pro' }) — imperative plan check (Clerk B2B billing)
  const { has } = useBilling();
  const { fmt, settings } = useChurchSettings();
  const [giving, setGiving] = useState([]);
  const [expenditures, setExpenditures] = useState([]);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const [month, setMonth] = useState(String(new Date().getMonth()));
  const [year, setYear] = useState(String(new Date().getFullYear()));
  const [emailTarget, setEmailTarget] = useState("");
  const [generated, setGenerated] = useState(false);

  useEffect(() => { loadData(); }, [month, year]);

  // Gate: Pro plan required (all hooks must be above this check)
  if (!has({ plan: 'pro' })) {
    return <UpgradePrompt plan="pro" message="Financial Reports are available on the Pro plan." />;
  }

  // Load only the selected month's records (server-side prefix filter) so the
  // totals stay complete regardless of how much history the church has.
  async function loadData() {
    setLoading(true);
    const prefix = `${year}-${String(parseInt(month) + 1).padStart(2, "0")}`;
    try {
      const [g, e] = await Promise.all([
        entities.Giving.filter({ date_startsWith: prefix, sort: "-date", limit: 10000 }),
        entities.Expenditure.filter({ date_startsWith: prefix, sort: "-date", limit: 10000 }),
      ]);
      setGiving(g); setExpenditures(e);
    } catch (err) {
      console.error("FinancialReports loadData failed:", err);
      setGiving([]); setExpenditures([]);
    } finally {
      setLoading(false);
    }
  }

  const monthIdx = parseInt(month);
  const yearNum = parseInt(year);

  // Timezone-safe month filtering — matches the shared PDF generator so the
  // on-screen figures and the downloaded/emailed report always agree.
  const filteredGiving = giving.filter(g => isInMonth(g.date, monthIdx, yearNum));
  const filteredExp = expenditures.filter(e => isInMonth(e.date, monthIdx, yearNum));

  const totalTithes = filteredGiving.filter(g=>g.type==="tithe").reduce((s,g)=>s+(g.amount||0),0);
  const totalOfferings = filteredGiving.filter(g=>g.type!=="tithe").reduce((s,g)=>s+(g.amount||0),0);
  const totalIncome = totalTithes + totalOfferings;
  const approvedExp = filteredExp.filter(e=>e.approval_status==="approved").reduce((s,e)=>s+(e.amount||0),0);
  const netBalance = totalIncome - approvedExp;

  function generatePDF() {
    generateFinancialReportPDF({
      monthIdx,
      year: yearNum,
      giving,
      expenditures,
      fmt,
      churchName: settings?.church_name,
    });
    setGenerated(true);
  }

  async function handleSendEmail() {
    if (!emailTarget) return;
    setSending(true);
    const body = `
      <h2>ChurchConnect — ${MONTHS[monthIdx]} ${year} Financial Report</h2>
      <table border="1" cellpadding="8" style="border-collapse:collapse;width:100%">
        <tr><th>Item</th><th>Amount</th></tr>
        <tr><td>Total Tithes</td><td>${fmt(totalTithes)}</td></tr>
        <tr><td>Total Offerings</td><td>${fmt(totalOfferings)}</td></tr>
        <tr><td>Total Income</td><td><strong>${fmt(totalIncome)}</strong></td></tr>
        <tr><td>Approved Expenditures</td><td>${fmt(approvedExp)}</td></tr>
        <tr><td><strong>Net Balance</strong></td><td><strong>${fmt(netBalance)}</strong></td></tr>
      </table>
      <p style="color:gray;font-size:12px">Generated by ChurchConnect CRM on ${format(new Date(),"MMMM d, yyyy")}</p>
    `;
    await sendEmail({
      to: emailTarget,
      subject: `Financial Report — ${MONTHS[monthIdx]} ${year}`,
      body,
      from_name: "ChurchConnect"
    });
    setSending(false);
    alert("Report sent successfully!");
  }

  if (loading) return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" /></div>;

  return (
    <div className="space-y-6 max-w-4xl">
      <div><h1 className="text-2xl font-bold">Financial Reports</h1><p className="text-muted-foreground text-sm">Generate and share monthly financial summaries</p></div>

      <div className="bg-white rounded-xl border border-border p-5 shadow-sm">
        <h2 className="font-semibold mb-4">Select Period</h2>
        <div className="flex flex-wrap gap-3 items-end">
          <div>
            <Label>Month</Label>
            <Select value={month} onValueChange={setMonth}>
              <SelectTrigger className="w-36 mt-1"><SelectValue /></SelectTrigger>
              <SelectContent>{MONTHS.map((m,i)=><SelectItem key={i} value={String(i)}>{m}</SelectItem>)}</SelectContent>
            </Select>
          </div>
          <div>
            <Label>Year</Label>
            <Select value={year} onValueChange={setYear}>
              <SelectTrigger className="w-28 mt-1"><SelectValue /></SelectTrigger>
              <SelectContent>{YEARS.map(y=><SelectItem key={y} value={y}>{y}</SelectItem>)}</SelectContent>
            </Select>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <StatCard title="Tithes" value={fmt(totalTithes)} icon={HandCoins} color="green" />
        <StatCard title="Offerings" value={fmt(totalOfferings)} icon={HandCoins} color="blue" />
        <StatCard title="Expenditures" value={fmt(approvedExp)} icon={HandCoins} color="red" />
        <StatCard title="Net Balance" value={fmt(netBalance)} icon={HandCoins} color={netBalance >= 0 ? "green" : "red"} />
      </div>

      <div className="bg-white rounded-xl border border-border p-5 shadow-sm space-y-4">
        <h2 className="font-semibold">Generate PDF Report</h2>
        <p className="text-muted-foreground text-sm">{filteredGiving.length} giving records and {filteredExp.length} expenditure records for {MONTHS[monthIdx]} {year}.</p>
        <Button onClick={generatePDF} className="bg-primary text-primary-foreground gap-2">
          <Download className="w-4 h-4" />Download PDF Report
        </Button>
      </div>

      <div className="bg-white rounded-xl border border-border p-5 shadow-sm space-y-4">
        <h2 className="font-semibold">Send Report by Email</h2>
        <div className="flex gap-3 flex-wrap items-end">
          <div className="flex-1 min-w-48">
            <Label>Recipient Email</Label>
            <input type="email" value={emailTarget} onChange={e=>setEmailTarget(e.target.value)} placeholder="pastor@church.org" className="mt-1 w-full border border-input rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring" />
          </div>
          <Button onClick={handleSendEmail} disabled={!emailTarget || sending} className="bg-primary text-primary-foreground gap-2">
            <Send className="w-4 h-4" />{sending ? "Sending..." : "Send Report"}
          </Button>
        </div>
      </div>
    </div>
  );
}
